name: flutter_get_law
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^1.0.2

  fluttertoast: ^4.0.1

  dio: ^3.0.9

  cookie_jar: ^1.0.1

  dio_cookie_manager: ^1.0.0

  shared_preferences: ^0.5.6+3

  cached_network_image: ^2.2.0+1

  share: ^0.6.5+4

  gzx_dropdown_menu: ^2.1.0

  open_file: ^3.0.1

  flustars: ^0.3.3

  flutter_swiper: ^1.1.6

  flutter_swipe_action_cell: ^1.3.2

  clipboard: ^0.1.2+8

  flutter_easyloading: ^1.1.3

  image_picker: ^0.6.7+6

  pull_to_refresh: ^1.6.1

  sqflite: ^1.3.0

  filesize: ^1.0.4

  city_pickers: ^0.1.30

  videos_player: ^0.1.3

  flutter_widget_from_html: ^0.5.0+3

  get: ^3.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/